[package]
name = "wasm-minesweeper"
version = "0.1.0"
authors = ["karthiknedunchezhiyan"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.63"
js-sys = "0.3.51"